apiVersion: apps/v1
kind: Deployment
metadata:
  name: LightSwitch
spec:
  replicas: 1
  selector:
    matchLabels:
      name: LightSwitch
  template:
    metadata:
      labels:
        name: LightSwitch
    spec:
      serviceAccountName: LightSwitch
      containers:
        - name: LightSwitch
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - LightSwitch
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "LightSwitch"
